CREATE TABLE ProgressionChords (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chord TEXT REFERENCES Notes(name),
    scale TEXT REFERENCES Scales(name),
    progressionid INTEGER REFERENCES Progressions(id) ON DELETE CASCADE,
    orderid INTEGER NOT NULL,
    voice TEXT NOT NULL,
    oct TEXT NOT NULL,
    active BOOLEAN DEFAULT false
);