INSERT INTO Chords (name, scale, notes)
VALUES 
    ('A', 'maj', 'A'),
    ('A', 'maj', 'Db'),
    ('A', 'maj', 'E'),
    ('Bb', 'maj', 'Bb'),
    ('Bb', 'maj', 'D'),
    ('Bb', 'maj', 'F'),
    ('B', 'maj', 'B'),
    ('B', 'maj', 'Eb'),
    ('B', 'maj', 'Gb'),
    ('C', 'maj', 'C'),
    ('C', 'maj', 'E'),
    ('C', 'maj', 'G'),
    ('Db', 'maj', 'Db'),
    ('Db','maj', 'F'),
    ('Db', 'maj', 'Ab'),
    ('D', 'maj', 'D'),
    ('D', 'maj', 'Gb'),
    ('D', 'maj', 'A'),
    ('Eb', 'maj', 'Eb'),
    ('Eb', 'maj', 'G'),
    ('Eb', 'maj', 'Bb'),
    ('E', 'maj', 'E'),
    ('E', 'maj', 'Ab'),
    ('E', 'maj', 'B'),
    ('F', 'maj', 'F'),
    ('F', 'maj', 'A'),
    ('F', 'maj', 'C'),
    ('Gb', 'maj', 'Gb'),
    ('Gb', 'maj', 'Bb'),
    ('Gb', 'maj', 'Db'),
    ('G', 'maj', 'G'),
    ('G', 'maj', 'B'),
    ('G', 'maj', 'D'),
    ('Ab', 'maj', 'Ab'),
    ('Ab', 'maj', 'C'),
    ('Ab', 'maj', 'Eb');